name: faunadb_http
version: 0.13.1
description: A pure Dart implementation of a FaunaDB client and provides query classes that closely mimic FQL functions.
homepage: https://github.com/gavanitrate/faunadb-http-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  json_annotation: ^4.0.0

dev_dependencies:
  json_serializable: ^4.0.3
  build_runner: ^1.12.1
  pedantic: ^1.11.0
